name: Meagan Bird
description: ramblings and musing 
meta_description: "Meagan Bird blog"

aboutPage: true

markdown: redcarpet
highlighter: pygments

paginate: 20
baseurl: /
domain_name: 'http://meaganbird.com'
google_analytics: 'UA-69349863-1'

disqus: false
disqus_shortname: 

# Details for the RSS feed generator
url:            'http://blog.meaganbird.com'
author:         'Meagan Bird'
authorTwitter:  '@megchirp'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
